SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='homepage_sections' AND COLUMN_NAME='body';

SELECT TOP 1 LEN(body) AS maxlen FROM homepage_sections ORDER BY LEN(body) DESC;